name: todo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  curved_navigation_bar: ^1.0.6
  animations: ^2.0.11
  tab_indicator_styler: ^2.0.0
  intl: ^0.20.2
  uuid: ^4.5.1
  animate_do: ^4.2.0
  flutter_riverpod: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/background.png"
    - "assets/clock.png"
    - "assets/light-1.png"
    - "assets/light-2.png"
